// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SHIMS.Context;

#nullable disable

namespace SHIMS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260223211222_RmUsrTitle")]
    partial class RmUsrTitle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("concurrencystamp");

                    b.Property<string>("Name")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("normalizedname");

                    b.HasKey("Id")
                        .HasName("pk_aspnetroles");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("aspnetroles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("claimtype");

                    b.Property<string>("ClaimValue")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("claimvalue");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("roleid");

                    b.HasKey("Id")
                        .HasName("pk_aspnetroleclaims");

                    b.HasIndex("RoleId");

                    b.ToTable("aspnetroleclaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("claimtype");

                    b.Property<string>("ClaimValue")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("claimvalue");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("pk_aspnetuserclaims");

                    b.HasIndex("UserId");

                    b.ToTable("aspnetuserclaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("loginprovider");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("providerkey");

                    b.Property<string>("ProviderDisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("providerdisplayname");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_aspnetuserlogins");

                    b.HasIndex("UserId");

                    b.ToTable("aspnetuserlogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("roleid");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_aspnetuserroles");

                    b.HasIndex("RoleId");

                    b.ToTable("aspnetuserroles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("loginprovider");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_aspnetusertokens");

                    b.ToTable("aspnetusertokens", (string)null);
                });

            modelBuilder.Entity("SHIMS.Context.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("accessfailedcount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("concurrencystamp");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("emailconfirmed");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("fullname");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockoutenabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockoutend");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("normalizedemail");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("normalizedusername");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(168)
                        .HasColumnType("character varying(168)")
                        .HasColumnName("passwordhash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("phonenumber");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phonenumberconfirmed");

                    b.Property<string>("SecurityStamp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("securitystamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("twofactorenabled");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_aspnetusers");

                    b.HasAlternateKey("UserName")
                        .HasName("ak_aspnetusers_username");

                    b.HasIndex("NormalizedEmail");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique();

                    b.ToTable("aspnetusers", (string)null);
                });

            modelBuilder.Entity("SHIMS.Models.Accounts.Payments", b =>
                {
                    b.Property<Guid>("PaymentsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("paymentsid");

                    b.Property<decimal>("Attendance")
                        .HasColumnType("numeric")
                        .HasColumnName("attendance");

                    b.Property<decimal>("Cash")
                        .HasColumnType("numeric")
                        .HasColumnName("cash");

                    b.Property<decimal>("Drugs")
                        .HasColumnType("numeric")
                        .HasColumnName("drugs");

                    b.PrimitiveCollection<Guid[]>("DrugsList")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("drugslist");

                    b.Property<decimal>("Labs")
                        .HasColumnType("numeric")
                        .HasColumnName("labs");

                    b.PrimitiveCollection<Guid[]>("LabsList")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("labslist");

                    b.Property<decimal>("MobileMoney")
                        .HasColumnType("numeric")
                        .HasColumnName("mobilemoney");

                    b.Property<Guid?>("PatientAttendancesID")
                        .HasColumnType("uuid")
                        .HasColumnName("patientattendancesid");

                    b.Property<Guid>("PatientsAttendancesID")
                        .HasColumnType("uuid")
                        .HasColumnName("patientsattendancesid");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paymentdate");

                    b.Property<decimal>("Registration")
                        .HasColumnType("numeric")
                        .HasColumnName("registration");

                    b.Property<decimal>("Services")
                        .HasColumnType("numeric")
                        .HasColumnName("services");

                    b.PrimitiveCollection<Guid[]>("ServicesList")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("serviceslist");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("username");

                    b.HasKey("PaymentsID")
                        .HasName("pk_payments");

                    b.HasIndex("PatientAttendancesID");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("SHIMS.Models.ConsultingRoom.Diagnoses", b =>
                {
                    b.Property<Guid>("DiagnosisID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("diagnosisid");

                    b.Property<string>("GDRG")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("gdrg");

                    b.Property<string>("ICD")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("icd");

                    b.Property<string>("SNOMED")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("snomed");

                    b.HasKey("DiagnosisID")
                        .HasName("pk_diagnoses");

                    b.HasIndex("ICD", "GDRG", "SNOMED")
                        .IsUnique();

                    b.ToTable("diagnoses", (string)null);
                });

            modelBuilder.Entity("SHIMS.Models.ConsultingRoom.PatientConsultation", b =>
                {
                    b.Property<Guid>("PatientConsultationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("patientconsultationid");

                    b.Property<byte>("AVPU")
                        .HasColumnType("smallint")
                        .HasColumnName("avpu");

                    b.Property<string>("Complaints")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("complaints");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateadded");

                    b.Property<string>("ODQ")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("odq");

                    b.Property<Guid?>("PatientAttendancesID")
                        .HasColumnType("uuid")
                        .HasColumnName("patientattendancesid");

                    b.Property<Guid>("PatientsAttendancesID")
                        .HasColumnType("uuid")
                        .HasColumnName("patientsattendancesid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("username");

                    b.HasKey("PatientConsultationID")
                        .HasName("pk_patientconsultations");

                    b.HasIndex("PatientAttendancesID");

                    b.ToTable("patientconsultations", (string)null);
                });

            modelBuilder.Entity("SHIMS.Models.ConsultingRoom.PatientDiagnosis", b =>
                {
                    b.Property<Guid>("PatientDiagnosisID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("patientdiagnosisid");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateadded");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<Guid?>("DiagnosesDiagnosisID")
                        .HasColumnType("uuid")
                        .HasColumnName("diagnosesdiagnosisid");

                    b.Property<Guid>("DiagnosisID")
                        .HasColumnType("uuid")
                        .HasColumnName("diagnosisid");

                    b.Property<Guid?>("PatientAttendancesID")
                        .HasColumnType("uuid")
                        .HasColumnName("patientattendancesid");

                    b.Property<Guid>("PatientsAttendancesID")
                        .HasColumnType("uuid")
                        .HasColumnName("patientsattendancesid");

                    b.PrimitiveCollection<Guid[]>("SecondaryDiagnoses")
                        .HasColumnType("uuid[]")
                        .HasColumnName("secondarydiagnoses");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("username");

                    b.HasKey("PatientDiagnosisID")
                        .HasName("pk_patientdiagnoses");

                    b.HasIndex("DiagnosesDiagnosisID");

                    b.HasIndex("PatientAttendancesID");

                    b.ToTable("patientdiagnoses", (string)null);
                });

            modelBuilder.Entity("SHIMS.Models.ConsultingRoom.PatientOutcomes", b =>
                {
                    b.Property<Guid>("PatientsAttendancesID")
                        .HasColumnType("uuid")
                        .HasColumnName("patientsattendancesid");

                    b.Property<string>("Notes")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("notes");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("outcome");

                    b.Property<DateTime>("OutcomeDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("outcomedate");

                    b.HasKey("PatientsAttendancesID")
                        .HasName("pk_patientoutcomes");

                    b.ToTable("patientoutcomes", (string)null);
                });

            modelBuilder.Entity("SHIMS.Models.ConsultingRoom.PatientSignsAndSymptoms", b =>
                {
                    b.Property<Guid>("PatientSignsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("patientsignsid");

                    b.Property<string>("SignAndSymptoms")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("signandsymptoms");

                    b.HasKey("PatientSignsID")
                        .HasName("pk_patientsignsandsymptoms");

                    b.ToTable("patientsignsandsymptoms", (string)null);
                });

            modelBuilder.Entity("SHIMS.Models.Drugs.Dispensing", b =>
                {
                    b.Property<Guid>("DrugPaymentsID")
                        .HasColumnType("uuid")
                        .HasColumnName("drugpaymentsid");

                    b.Property<DateTime>("DateDispensed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datedispensed");

                    b.Property<byte>("QuantityDispensed")
                        .HasColumnType("smallint")
                        .HasColumnName("quantitydispensed");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("username");

                    b.HasKey("DrugPaymentsID")
                        .HasName("pk_dispensings");

                    b.ToTable("dispensings", (string)null);
                });

            modelBuilder.Entity("SHIMS.Models.Drugs.DispensingCalculations", b =>
                {
                    b.Property<Guid>("DrugsRequestsID")
                        .HasColumnType("uuid")
                        .HasColumnName("drugsrequestsid");

                    b.Property<DateTime>("DateDone")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datedone");

                    b.Property<string>("Notes")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("notes");

                    b.Property<byte>("Quantity")
                        .HasColumnType("smallint")
                        .HasColumnName("quantity");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("username");

                    b.HasKey("DrugsRequestsID")
                        .HasName("pk_dispensingcalculations");

                    b.ToTable("dispensingcalculations", (string)null);
                });

            modelBuilder.Entity("SHIMS.Models.Drugs.DrugPayments", b =>
                {
                    b.Property<Guid>("DispensingCaculationsID")
                        .HasColumnType("uuid")
                        .HasColumnName("dispensingcaculationsid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("DatePaid")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datepaid");

                    b.Property<Guid?>("PaymentTypesID")
                        .HasColumnType("uuid")
                        .HasColumnName("paymenttypesid");

                    b.Property<byte>("QuantityPaid")
                        .HasColumnType("smallint")
                        .HasColumnName("quantitypaid");

                    b.Property<string>("Receipt")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("receipt");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("username");

                    b.HasKey("DispensingCaculationsID")
                        .HasName("pk_drugpayments");

                    b.ToTable("drugpayments", (string)null);
                });

            modelBuilder.Entity("SHIMS.Models.Drugs.Drugs", b =>
                {
                    b.Property<Guid>("DrugsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("drugsid");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateadded");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.Property<string>("Drug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("drug");

                    b.Property<string>("Tags")
                        .HasColumnType("text")
                        .HasColumnName("tags");

                    b.HasKey("DrugsID")
                        .HasName("pk_drugs");

                    b.ToTable("drugs", (string)null);
                });

            modelBuilder.Entity("SHIMS.Models.Drugs.DrugsRequests", b =>
                {
                    b.Property<Guid>("DrugsRequestsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("drugsrequestsid");

                    b.Property<DateTime>("DateRequested")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("daterequested");

                    b.Property<byte>("Days")
                        .HasColumnType("smallint")
                        .HasColumnName("days");

                    b.Property<Guid?>("DrugsID")
                        .HasColumnType("uuid")
                        .HasColumnName("drugsid");

                    b.Property<byte>("Frequency")
                        .HasColumnType("smallint")
                        .HasColumnName("frequency");

                    b.Property<bool>("IsDispensed")
                        .HasColumnType("boolean")
                        .HasColumnName("isdispensed");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean")
                        .HasColumnName("ispaid");

                    b.Property<Guid>("PatientsAttendancesID")
                        .HasColumnType("uuid")
                        .HasColumnName("patientsattendancesid");

                    b.Property<byte>("QuantityRequested")
                        .HasColumnType("smallint")
                        .HasColumnName("quantityrequested");

                    b.Property<Guid>("SchemeDrugsID")
                        .HasColumnType("uuid")
                        .HasColumnName("schemedrugsid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("username");

                    b.HasKey("DrugsRequestsID")
                        .HasName("pk_drugsrequests");

                    b.HasIndex("DrugsID");

                    b.HasIndex("PatientsAttendancesID");

                    b.HasIndex("SchemeDrugsID");

                    b.ToTable("drugsrequests", (string)null);
                });

            modelBuilder.Entity("SHIMS.Models.Drugs.DrugsStock", b =>
                {
                    b.Property<Guid>("DrugsStockID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("drugsstockid");

                    b.Property<Guid>("DrugsID")
                        .HasColumnType("uuid")
                        .HasColumnName("drugsid");

                    b.Property<short>("Quantity")
                        .HasColumnType("smallint")
                        .HasColumnName("quantity");

                    b.Property<DateTime>("TranDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trandate");

                    b.HasKey("DrugsStockID")
                        .HasName("pk_drugsstocks");

                    b.HasIndex("DrugsID");

                    b.ToTable("drugsstocks", (string)null);
                });

            modelBuilder.Entity("SHIMS.Models.Labs.LabGroups", b =>
                {
                    b.Property<Guid>("LabGroupsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("labgroupsid");

                    b.Property<string>("LabDescription")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("labdescription");

                    b.Property<string>("LabGroup")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("labgroup");

                    b.HasKey("LabGroupsID")
                        .HasName("pk_laboratories");

                    b.ToTable("laboratories", (string)null);
                });

            modelBuilder.Entity("SHIMS.Models.Labs.LabParameters", b =>
                {
                    b.Property<int>("LabParametersID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("labparametersid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LabParametersID"));

                    b.Property<int>("LabGroupsID")
                        .HasColumnType("integer")
                        .HasColumnName("labgroupsid");

                    b.Property<Guid?>("LabGroupsID1")
                        .HasColumnType("uuid")
                        .HasColumnName("labgroupsid1");

                    b.Property<string>("LabParameter")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("labparameter");

                    b.Property<short>("Order")
                        .HasColumnType("smallint")
                        .HasColumnName("order");

                    b.HasKey("LabParametersID")
                        .HasName("pk_labparameters");

                    b.HasIndex("LabGroupsID1");

                    b.ToTable("labparameters", (string)null);
                });

            modelBuilder.Entity("SHIMS.Models.Labs.LabPayment", b =>
                {
                    b.Property<Guid>("LabRequestsID")
                        .HasColumnType("uuid")
                        .HasColumnName("labrequestsid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("DatePaid")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datepaid");

                    b.Property<string>("PaymentReceiver")
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("paymentreceiver");

                    b.Property<Guid?>("PaymentTypesID")
                        .HasColumnType("uuid")
                        .HasColumnName("paymenttypesid");

                    b.Property<string>("Receipt")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("receipt");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("username");

                    b.HasKey("LabRequestsID")
                        .HasName("pk_labpayments");

                    b.ToTable("labpayments", (string)null);
                });

            modelBuilder.Entity("SHIMS.Models.Labs.LabRequests", b =>
                {
                    b.Property<Guid>("LabRequestsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("labrequestsid");

                    b.Property<DateTime>("DateRequested")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("daterequested");

                    b.Property<Guid?>("PatientAttendancesID")
                        .HasColumnType("uuid")
                        .HasColumnName("patientattendancesid");

                    b.Property<Guid>("PatientsAttendancesID")
                        .HasColumnType("uuid")
                        .HasColumnName("patientsattendancesid");

                    b.Property<Guid>("SchemeLabsID")
                        .HasColumnType("uuid")
                        .HasColumnName("schemelabsid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("username");

                    b.HasKey("LabRequestsID")
                        .HasName("pk_labrequests");

                    b.HasIndex("PatientAttendancesID");

                    b.HasIndex("SchemeLabsID");

                    b.ToTable("labrequests", (string)null);
                });

            modelBuilder.Entity("SHIMS.Models.Labs.LabResults", b =>
                {
                    b.Property<Guid>("LabPaymentID")
                        .HasColumnType("uuid")
                        .HasColumnName("labpaymentid");

                    b.Property<DateTime>("DateTested")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datetested");

                    b.Property<Guid>("LabParametersID")
                        .HasColumnType("uuid")
                        .HasColumnName("labparametersid");

                    b.Property<int?>("LabParametersID1")
                        .HasColumnType("integer")
                        .HasColumnName("labparametersid1");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("result");

                    b.Property<string>("ServerName")
                        .HasColumnType("text")
                        .HasColumnName("servername");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("username");

                    b.HasKey("LabPaymentID")
                        .HasName("pk_labresults");

                    b.HasIndex("LabParametersID1");

                    b.ToTable("labresults", (string)null);
                });

            modelBuilder.Entity("SHIMS.Models.OPD.Vitals", b =>
                {
                    b.Property<Guid>("VitalsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("vitalsid");

                    b.Property<string>("Complaints")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("complaints");

                    b.Property<DateTime>("DateSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateseen");

                    b.Property<double>("Diastol")
                        .HasColumnType("double precision")
                        .HasColumnName("diastol");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("notes");

                    b.Property<Guid?>("PatientAttendancesID")
                        .HasColumnType("uuid")
                        .HasColumnName("patientattendancesid");

                    b.Property<Guid>("PatientsAttendancesID")
                        .HasColumnType("uuid")
                        .HasColumnName("patientsattendancesid");

                    b.Property<double>("Pulse")
                        .HasColumnType("double precision")
                        .HasColumnName("pulse");

                    b.Property<double>("Respiration")
                        .HasColumnType("double precision")
                        .HasColumnName("respiration");

                    b.Property<double?>("SPO2")
                        .HasColumnType("double precision")
                        .HasColumnName("spo2");

                    b.Property<double>("Systol")
                        .HasColumnType("double precision")
                        .HasColumnName("systol");

                    b.Property<double>("Temperature")
                        .HasColumnType("double precision")
                        .HasColumnName("temperature");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("username");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision")
                        .HasColumnName("weight");

                    b.HasKey("VitalsID")
                        .HasName("pk_vitals");

                    b.HasIndex("PatientAttendancesID");

                    b.ToTable("vitals", (string)null);
                });

            modelBuilder.Entity("SHIMS.Models.Records.PatientAttendance", b =>
                {
                    b.Property<Guid>("PatientAttendancesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("patientattendancesid");

                    b.Property<DateTime>("DateSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateseen");

                    b.Property<Guid>("PatientSchemesID")
                        .HasColumnType("uuid")
                        .HasColumnName("patientschemesid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("username");

                    b.Property<string>("VisitType")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("visittype");

                    b.HasKey("PatientAttendancesID")
                        .HasName("pk_patientattendances");

                    b.HasIndex("PatientSchemesID");

                    b.ToTable("patientattendances", (string)null);
                });

            modelBuilder.Entity("SHIMS.Models.Records.PatientSchemes", b =>
                {
                    b.Property<Guid>("PatientSchemesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("patientschemesid");

                    b.Property<string>("CardID")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("cardid");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expirydate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastupdatedate");

                    b.Property<Guid>("PatientsID")
                        .HasColumnType("uuid")
                        .HasColumnName("patientsid");

                    b.Property<Guid>("SchemesID")
                        .HasColumnType("uuid")
                        .HasColumnName("schemesid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("username");

                    b.HasKey("PatientSchemesID")
                        .HasName("pk_patientschemes");

                    b.ToTable("patientschemes", (string)null);
                });

            modelBuilder.Entity("SHIMS.Models.Records.Patients", b =>
                {
                    b.Property<Guid>("PatientsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("patientsid");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateofbirth");

                    b.Property<string>("HospitalID")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hospitalid");

                    b.Property<string>("OtherNames")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("othernames");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phonenumber");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("sex");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("surname");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("username");

                    b.HasKey("PatientsID")
                        .HasName("pk_patients");

                    b.ToTable("patients", (string)null);
                });

            modelBuilder.Entity("SHIMS.Models.Schemes.SchemeDrugs", b =>
                {
                    b.Property<Guid>("SchemDrugsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("schemdrugsid");

                    b.Property<DateTime>("DateSet")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateset");

                    b.Property<Guid>("DrugsID")
                        .HasColumnType("uuid")
                        .HasColumnName("drugsid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<Guid>("SchemesID")
                        .HasColumnType("uuid")
                        .HasColumnName("schemesid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("username");

                    b.HasKey("SchemDrugsID")
                        .HasName("pk_schemedrugs");

                    b.HasIndex("DrugsID");

                    b.HasIndex("SchemesID");

                    b.ToTable("schemedrugs", (string)null);
                });

            modelBuilder.Entity("SHIMS.Models.Schemes.SchemeLabs", b =>
                {
                    b.Property<Guid>("SchemeLabsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("schemelabsid");

                    b.Property<DateTime>("DateSet")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateset");

                    b.Property<Guid?>("LabGroupsID")
                        .HasColumnType("uuid")
                        .HasColumnName("labgroupsid");

                    b.Property<Guid>("LabsGroupID")
                        .HasColumnType("uuid")
                        .HasColumnName("labsgroupid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<Guid>("SchemesID")
                        .HasColumnType("uuid")
                        .HasColumnName("schemesid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("username");

                    b.HasKey("SchemeLabsID")
                        .HasName("pk_schemelabs");

                    b.HasIndex("LabGroupsID");

                    b.HasIndex("SchemesID");

                    b.ToTable("schemelabs", (string)null);
                });

            modelBuilder.Entity("SHIMS.Models.Schemes.SchemeServices", b =>
                {
                    b.Property<Guid>("SchemeServicesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("schemeservicesid");

                    b.Property<DateTime>("DateSet")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateset");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<Guid>("SchemesID")
                        .HasColumnType("uuid")
                        .HasColumnName("schemesid");

                    b.Property<Guid>("ServicesID")
                        .HasColumnType("uuid")
                        .HasColumnName("servicesid");

                    b.Property<int?>("ServicesID1")
                        .HasColumnType("integer")
                        .HasColumnName("servicesid1");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("username");

                    b.HasKey("SchemeServicesID")
                        .HasName("pk_schemeservices");

                    b.HasIndex("SchemesID");

                    b.HasIndex("ServicesID1");

                    b.ToTable("schemeservices", (string)null);
                });

            modelBuilder.Entity("SHIMS.Models.Schemes.Schemes", b =>
                {
                    b.Property<Guid>("SchemesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("schemesid");

                    b.Property<string>("Coverage")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("coverage");

                    b.Property<decimal>("MaxPayable")
                        .HasColumnType("numeric")
                        .HasColumnName("maxpayable");

                    b.Property<decimal>("Recovery")
                        .HasColumnType("numeric")
                        .HasColumnName("recovery");

                    b.Property<string>("SchemeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("schemename");

                    b.HasKey("SchemesID")
                        .HasName("pk_schemes");

                    b.ToTable("schemes", (string)null);
                });

            modelBuilder.Entity("SHIMS.Models.Services.ServicePayment", b =>
                {
                    b.Property<Guid>("ServiceRequestID")
                        .HasColumnType("uuid")
                        .HasColumnName("servicerequestid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("DatePaid")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datepaid");

                    b.Property<Guid>("PatientsAttendancesID")
                        .HasColumnType("uuid")
                        .HasColumnName("patientsattendancesid");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("paymentmethod");

                    b.Property<string>("Receipt")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("receipt");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("username");

                    b.HasKey("ServiceRequestID")
                        .HasName("pk_servicepayments");

                    b.ToTable("servicepayments", (string)null);
                });

            modelBuilder.Entity("SHIMS.Models.Services.ServiceRendering", b =>
                {
                    b.Property<Guid>("ServicePaymentID")
                        .HasColumnType("uuid")
                        .HasColumnName("servicepaymentid");

                    b.Property<DateTime>("DateServed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateserved");

                    b.Property<Guid>("PatientsAttendancesID")
                        .HasColumnType("uuid")
                        .HasColumnName("patientsattendancesid");

                    b.Property<string>("Report")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("report");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("username");

                    b.HasKey("ServicePaymentID")
                        .HasName("pk_servicerenderings");

                    b.ToTable("servicerenderings", (string)null);
                });

            modelBuilder.Entity("SHIMS.Models.Services.ServiceRequest", b =>
                {
                    b.Property<Guid>("ServiceRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("servicerequestid");

                    b.Property<DateTime>("DateRequested")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("daterequested");

                    b.Property<byte>("Frequency")
                        .HasColumnType("smallint")
                        .HasColumnName("frequency");

                    b.Property<Guid?>("PatientAttendancesID")
                        .HasColumnType("uuid")
                        .HasColumnName("patientattendancesid");

                    b.Property<Guid>("PatientsAttendancesID")
                        .HasColumnType("uuid")
                        .HasColumnName("patientsattendancesid");

                    b.Property<Guid>("SchemeServicesID")
                        .HasColumnType("uuid")
                        .HasColumnName("schemeservicesid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("username");

                    b.HasKey("ServiceRequestID")
                        .HasName("pk_servicerequests");

                    b.HasIndex("PatientAttendancesID");

                    b.HasIndex("SchemeServicesID");

                    b.ToTable("servicerequests", (string)null);
                });

            modelBuilder.Entity("SHIMS.Models.Services.Services", b =>
                {
                    b.Property<int>("ServicesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("servicesid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ServicesID"));

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("service");

                    b.Property<string>("ServiceGroup")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("servicegroup");

                    b.HasKey("ServicesID")
                        .HasName("pk_services");

                    b.ToTable("services", (string)null);
                });

            modelBuilder.Entity("SHIMS.Models.Wards.WardAdmissions", b =>
                {
                    b.Property<Guid>("WardAdmissionsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("wardadmissionsid");

                    b.Property<DateTime>("DateAdmitted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateadmitted");

                    b.Property<DateTime?>("DateDischarged")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datedischarged");

                    b.Property<Guid?>("PatientAttendancesID")
                        .HasColumnType("uuid")
                        .HasColumnName("patientattendancesid");

                    b.Property<Guid>("PatientsAttendancesID")
                        .HasColumnType("uuid")
                        .HasColumnName("patientsattendancesid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("username");

                    b.Property<Guid>("WardsID")
                        .HasColumnType("uuid")
                        .HasColumnName("wardsid");

                    b.HasKey("WardAdmissionsID")
                        .HasName("pk_wardadmissions");

                    b.HasIndex("PatientAttendancesID");

                    b.HasIndex("WardsID");

                    b.ToTable("wardadmissions", (string)null);
                });

            modelBuilder.Entity("SHIMS.Models.Wards.Wards", b =>
                {
                    b.Property<Guid>("WardsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("wardsid");

                    b.Property<short>("Capacity")
                        .HasColumnType("smallint")
                        .HasColumnName("capacity");

                    b.Property<string>("Ward")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ward");

                    b.Property<string>("WardTags")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("wardtags");

                    b.HasKey("WardsID")
                        .HasName("pk_wards");

                    b.HasIndex("Ward")
                        .IsUnique();

                    b.ToTable("wards", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_aspnetroleclaims_aspnetroles_roleid");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("SHIMS.Context.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_aspnetuserclaims_aspnetusers_userid");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("SHIMS.Context.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_aspnetuserlogins_aspnetusers_userid");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_aspnetuserroles_aspnetroles_roleid");

                    b.HasOne("SHIMS.Context.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_aspnetuserroles_aspnetusers_userid");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("SHIMS.Context.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_aspnetusertokens_aspnetusers_userid");
                });

            modelBuilder.Entity("SHIMS.Models.Accounts.Payments", b =>
                {
                    b.HasOne("SHIMS.Models.Records.PatientAttendance", "PatientAttendance")
                        .WithMany()
                        .HasForeignKey("PatientAttendancesID")
                        .HasConstraintName("fk_payments_patientattendances_patientattendancesid");

                    b.Navigation("PatientAttendance");
                });

            modelBuilder.Entity("SHIMS.Models.ConsultingRoom.PatientConsultation", b =>
                {
                    b.HasOne("SHIMS.Models.Records.PatientAttendance", "PatientAttendance")
                        .WithMany()
                        .HasForeignKey("PatientAttendancesID")
                        .HasConstraintName("fk_patientconsultations_patientattendances_patientattendancesid");

                    b.Navigation("PatientAttendance");
                });

            modelBuilder.Entity("SHIMS.Models.ConsultingRoom.PatientDiagnosis", b =>
                {
                    b.HasOne("SHIMS.Models.ConsultingRoom.Diagnoses", "Diagnoses")
                        .WithMany()
                        .HasForeignKey("DiagnosesDiagnosisID")
                        .HasConstraintName("fk_patientdiagnoses_diagnoses_diagnosesdiagnosisid");

                    b.HasOne("SHIMS.Models.Records.PatientAttendance", "PatientAttendance")
                        .WithMany()
                        .HasForeignKey("PatientAttendancesID")
                        .HasConstraintName("fk_patientdiagnoses_patientattendances_patientattendancesid");

                    b.Navigation("Diagnoses");

                    b.Navigation("PatientAttendance");
                });

            modelBuilder.Entity("SHIMS.Models.ConsultingRoom.PatientOutcomes", b =>
                {
                    b.HasOne("SHIMS.Models.Records.PatientAttendance", "PatientAttendance")
                        .WithMany()
                        .HasForeignKey("PatientsAttendancesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_patientoutcomes_patientattendances_patientsattendancesid");

                    b.Navigation("PatientAttendance");
                });

            modelBuilder.Entity("SHIMS.Models.Drugs.Dispensing", b =>
                {
                    b.HasOne("SHIMS.Models.Drugs.DrugPayments", "DrugPayments")
                        .WithOne("Dispensing")
                        .HasForeignKey("SHIMS.Models.Drugs.Dispensing", "DrugPaymentsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dispensings_drugpayments_drugpaymentsid");

                    b.Navigation("DrugPayments");
                });

            modelBuilder.Entity("SHIMS.Models.Drugs.DispensingCalculations", b =>
                {
                    b.HasOne("SHIMS.Models.Drugs.DrugsRequests", "DrugsRequests")
                        .WithOne("DispensingCalculations")
                        .HasForeignKey("SHIMS.Models.Drugs.DispensingCalculations", "DrugsRequestsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dispensingcalculations_drugsrequests_drugsrequestsid");

                    b.Navigation("DrugsRequests");
                });

            modelBuilder.Entity("SHIMS.Models.Drugs.DrugPayments", b =>
                {
                    b.HasOne("SHIMS.Models.Drugs.DispensingCalculations", "DispensingCalculations")
                        .WithOne("DrugPayments")
                        .HasForeignKey("SHIMS.Models.Drugs.DrugPayments", "DispensingCaculationsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_drugpayments_dispensingcalculations_dispensingcaculationsid");

                    b.Navigation("DispensingCalculations");
                });

            modelBuilder.Entity("SHIMS.Models.Drugs.DrugsRequests", b =>
                {
                    b.HasOne("SHIMS.Models.Drugs.Drugs", null)
                        .WithMany("PatientDrugs")
                        .HasForeignKey("DrugsID")
                        .HasConstraintName("fk_drugsrequests_drugs_drugsid");

                    b.HasOne("SHIMS.Models.Records.PatientAttendance", "PatientsAttendances")
                        .WithMany()
                        .HasForeignKey("PatientsAttendancesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_drugsrequests_patientattendances_patientsattendancesid");

                    b.HasOne("SHIMS.Models.Schemes.SchemeDrugs", "SchemeDrugs")
                        .WithMany("DrugsRequests")
                        .HasForeignKey("SchemeDrugsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_drugsrequests_schemedrugs_schemedrugsid");

                    b.Navigation("PatientsAttendances");

                    b.Navigation("SchemeDrugs");
                });

            modelBuilder.Entity("SHIMS.Models.Drugs.DrugsStock", b =>
                {
                    b.HasOne("SHIMS.Models.Drugs.Drugs", "Drugs")
                        .WithMany("DrugsStocks")
                        .HasForeignKey("DrugsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_drugsstocks_drugs_drugsid");

                    b.Navigation("Drugs");
                });

            modelBuilder.Entity("SHIMS.Models.Labs.LabParameters", b =>
                {
                    b.HasOne("SHIMS.Models.Labs.LabGroups", "LabGroup")
                        .WithMany("LabParameters")
                        .HasForeignKey("LabGroupsID1")
                        .HasConstraintName("fk_labparameters_laboratories_labgroupsid1");

                    b.Navigation("LabGroup");
                });

            modelBuilder.Entity("SHIMS.Models.Labs.LabPayment", b =>
                {
                    b.HasOne("SHIMS.Models.Labs.LabRequests", "LabRequests")
                        .WithOne("LabPayment")
                        .HasForeignKey("SHIMS.Models.Labs.LabPayment", "LabRequestsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_labpayments_labrequests_labrequestsid");

                    b.Navigation("LabRequests");
                });

            modelBuilder.Entity("SHIMS.Models.Labs.LabRequests", b =>
                {
                    b.HasOne("SHIMS.Models.Records.PatientAttendance", "PatientAttendance")
                        .WithMany()
                        .HasForeignKey("PatientAttendancesID")
                        .HasConstraintName("fk_labrequests_patientattendances_patientattendancesid");

                    b.HasOne("SHIMS.Models.Schemes.SchemeLabs", "SchemeLabs")
                        .WithMany("LabRequests")
                        .HasForeignKey("SchemeLabsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_labrequests_schemelabs_schemelabsid");

                    b.Navigation("PatientAttendance");

                    b.Navigation("SchemeLabs");
                });

            modelBuilder.Entity("SHIMS.Models.Labs.LabResults", b =>
                {
                    b.HasOne("SHIMS.Models.Labs.LabParameters", "LabParameter")
                        .WithMany()
                        .HasForeignKey("LabParametersID1")
                        .HasConstraintName("fk_labresults_labparameters_labparametersid1");

                    b.HasOne("SHIMS.Models.Labs.LabPayment", "LabPayment")
                        .WithOne("LabResults")
                        .HasForeignKey("SHIMS.Models.Labs.LabResults", "LabPaymentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_labresults_labpayments_labpaymentid");

                    b.Navigation("LabParameter");

                    b.Navigation("LabPayment");
                });

            modelBuilder.Entity("SHIMS.Models.OPD.Vitals", b =>
                {
                    b.HasOne("SHIMS.Models.Records.PatientAttendance", "PatientAttendance")
                        .WithMany()
                        .HasForeignKey("PatientAttendancesID")
                        .HasConstraintName("fk_vitals_patientattendances_patientattendancesid");

                    b.Navigation("PatientAttendance");
                });

            modelBuilder.Entity("SHIMS.Models.Records.PatientAttendance", b =>
                {
                    b.HasOne("SHIMS.Models.Records.PatientSchemes", "PatientSchemes")
                        .WithMany()
                        .HasForeignKey("PatientSchemesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_patientattendances_patientschemes_patientschemesid");

                    b.Navigation("PatientSchemes");
                });

            modelBuilder.Entity("SHIMS.Models.Schemes.SchemeDrugs", b =>
                {
                    b.HasOne("SHIMS.Models.Drugs.Drugs", "Drugs")
                        .WithMany()
                        .HasForeignKey("DrugsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_schemedrugs_drugs_drugsid");

                    b.HasOne("SHIMS.Models.Schemes.Schemes", "Schemes")
                        .WithMany()
                        .HasForeignKey("SchemesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_schemedrugs_schemes_schemesid");

                    b.Navigation("Drugs");

                    b.Navigation("Schemes");
                });

            modelBuilder.Entity("SHIMS.Models.Schemes.SchemeLabs", b =>
                {
                    b.HasOne("SHIMS.Models.Labs.LabGroups", "LabGroups")
                        .WithMany("SchemeLabs")
                        .HasForeignKey("LabGroupsID")
                        .HasConstraintName("fk_schemelabs_laboratories_labgroupsid");

                    b.HasOne("SHIMS.Models.Schemes.Schemes", "Schemes")
                        .WithMany()
                        .HasForeignKey("SchemesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_schemelabs_schemes_schemesid");

                    b.Navigation("LabGroups");

                    b.Navigation("Schemes");
                });

            modelBuilder.Entity("SHIMS.Models.Schemes.SchemeServices", b =>
                {
                    b.HasOne("SHIMS.Models.Schemes.Schemes", "Schemes")
                        .WithMany()
                        .HasForeignKey("SchemesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_schemeservices_schemes_schemesid");

                    b.HasOne("SHIMS.Models.Services.Services", "Services")
                        .WithMany("SchemeServices")
                        .HasForeignKey("ServicesID1")
                        .HasConstraintName("fk_schemeservices_services_servicesid1");

                    b.Navigation("Schemes");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("SHIMS.Models.Services.ServicePayment", b =>
                {
                    b.HasOne("SHIMS.Models.Services.ServiceRequest", "ServiceRequest")
                        .WithOne("ServicePayment")
                        .HasForeignKey("SHIMS.Models.Services.ServicePayment", "ServiceRequestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_servicepayments_servicerequests_servicerequestid");

                    b.Navigation("ServiceRequest");
                });

            modelBuilder.Entity("SHIMS.Models.Services.ServiceRendering", b =>
                {
                    b.HasOne("SHIMS.Models.Services.ServicePayment", "ServicePayment")
                        .WithOne("ServiceRendering")
                        .HasForeignKey("SHIMS.Models.Services.ServiceRendering", "ServicePaymentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_servicerenderings_servicepayments_servicepaymentid");

                    b.Navigation("ServicePayment");
                });

            modelBuilder.Entity("SHIMS.Models.Services.ServiceRequest", b =>
                {
                    b.HasOne("SHIMS.Models.Records.PatientAttendance", "PatientAttendance")
                        .WithMany()
                        .HasForeignKey("PatientAttendancesID")
                        .HasConstraintName("fk_servicerequests_patientattendances_patientattendancesid");

                    b.HasOne("SHIMS.Models.Schemes.SchemeServices", "SchemeServices")
                        .WithMany("ServiceRequests")
                        .HasForeignKey("SchemeServicesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_servicerequests_schemeservices_schemeservicesid");

                    b.Navigation("PatientAttendance");

                    b.Navigation("SchemeServices");
                });

            modelBuilder.Entity("SHIMS.Models.Wards.WardAdmissions", b =>
                {
                    b.HasOne("SHIMS.Models.Records.PatientAttendance", "PatientAttendance")
                        .WithMany()
                        .HasForeignKey("PatientAttendancesID")
                        .HasConstraintName("fk_wardadmissions_patientattendances_patientattendancesid");

                    b.HasOne("SHIMS.Models.Wards.Wards", "Wards")
                        .WithMany()
                        .HasForeignKey("WardsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wardadmissions_wards_wardsid");

                    b.Navigation("PatientAttendance");

                    b.Navigation("Wards");
                });

            modelBuilder.Entity("SHIMS.Models.Drugs.DispensingCalculations", b =>
                {
                    b.Navigation("DrugPayments");
                });

            modelBuilder.Entity("SHIMS.Models.Drugs.DrugPayments", b =>
                {
                    b.Navigation("Dispensing");
                });

            modelBuilder.Entity("SHIMS.Models.Drugs.Drugs", b =>
                {
                    b.Navigation("DrugsStocks");

                    b.Navigation("PatientDrugs");
                });

            modelBuilder.Entity("SHIMS.Models.Drugs.DrugsRequests", b =>
                {
                    b.Navigation("DispensingCalculations");
                });

            modelBuilder.Entity("SHIMS.Models.Labs.LabGroups", b =>
                {
                    b.Navigation("LabParameters");

                    b.Navigation("SchemeLabs");
                });

            modelBuilder.Entity("SHIMS.Models.Labs.LabPayment", b =>
                {
                    b.Navigation("LabResults");
                });

            modelBuilder.Entity("SHIMS.Models.Labs.LabRequests", b =>
                {
                    b.Navigation("LabPayment");
                });

            modelBuilder.Entity("SHIMS.Models.Schemes.SchemeDrugs", b =>
                {
                    b.Navigation("DrugsRequests");
                });

            modelBuilder.Entity("SHIMS.Models.Schemes.SchemeLabs", b =>
                {
                    b.Navigation("LabRequests");
                });

            modelBuilder.Entity("SHIMS.Models.Schemes.SchemeServices", b =>
                {
                    b.Navigation("ServiceRequests");
                });

            modelBuilder.Entity("SHIMS.Models.Services.ServicePayment", b =>
                {
                    b.Navigation("ServiceRendering");
                });

            modelBuilder.Entity("SHIMS.Models.Services.ServiceRequest", b =>
                {
                    b.Navigation("ServicePayment");
                });

            modelBuilder.Entity("SHIMS.Models.Services.Services", b =>
                {
                    b.Navigation("SchemeServices");
                });
#pragma warning restore 612, 618
        }
    }
}
