using Microsoft.EntityFrameworkCore;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ShimsServer.Models.Schemes
{
    /// <summary>
    /// Represents an insurance scheme that defines coverage types and reimbursement policies.
    /// </summary>
    /// <remarks>
    /// Insurance schemes determine how much the system will reimburse for patient services.
    /// Each scheme specifies a coverage type (Full, Relative, or Fixed) and sets the maximum
    /// amount the scheme will pay (MaxPayable) and the recovery percentage for visits (Recovery).
    /// </remarks>
    [Index(nameof(SchemeName), IsUnique = true)]
    public class Schemes
    {
        /// <summary>
        /// Gets or sets the unique identifier for the scheme.
        /// </summary>
        /// <remarks>
        /// This is a UUID (Guid) that is automatically generated by the database.
        /// </remarks>
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid SchemesID { get; set; }

        /// <summary>
        /// Gets or sets the name of the insurance scheme.
        /// </summary>
        /// <remarks>
        /// The scheme name must be between 3 and 50 characters in length and should be unique.
        /// Examples: "Gold Plan", "Standard Coverage", "Basic Insurance"
        /// </remarks>
        [Required, StringLength(50, MinimumLength = 3)]
        public required string SchemeName { get; set; }

        /// <summary>
        /// Gets or sets the coverage type of the scheme.
        /// </summary>
        /// <remarks>
        /// The coverage type determines how reimbursement is calculated:
        /// - "Full": The scheme covers the full cost of services
        /// - "Relative": The scheme covers a percentage of services (determined by Recovery rate)
        /// - "Fixed": The scheme covers a fixed amount per service
        /// </remarks>
        [Required]
        [StringLength(30)]
        [AllowedValues(["Full", "Relative", "Fixed"])]
        public required string Coverage { get; set; }

        /// <summary>
        /// Gets or sets the maximum amount the scheme will reimburse in a billing period.
        /// </summary>
        /// <remarks>
        /// Once this amount is reached, the scheme will not reimburse any additional costs.
        /// Default value is 100. Must be greater than or equal to 0.
        /// The value represents currency in the smallest unit (e.g., cents for USD).
        /// 
        /// <strong>Required when:</strong> Coverage type is "Fixed"
        /// <strong>Optional when:</strong> Coverage type is "Full" or "Relative"
        /// </remarks>
        [DefaultValue(100)]
        [Range(0, double.MaxValue)]
        public decimal MaxPayable { get; set; }

        /// <summary>
        /// Gets or sets the recovery percentage for patient visits under this scheme.
        /// </summary>
        /// <remarks>
        /// This percentage determines how much of the service cost the scheme will reimburse per visit.
        /// Valid range is 1 to 100 percent. Default value is 100 (full reimbursement per visit).
        /// This value is particularly important for schemes with "Relative" coverage type.
        /// 
        /// <strong>Required when:</strong> Coverage type is "Relative"
        /// <strong>Optional when:</strong> Coverage type is "Full" or "Fixed"
        /// </remarks>
        [DefaultValue(100)]
        [Range(0, 100.0)]
        public decimal Recovery { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the scheme is currently active.
        /// </summary>
        /// <remarks>
        /// When set to false, the scheme can no longer be assigned to new patients or used for reimbursement calculations.
        /// Default value is true. Consider archiving rather than deleting schemes for audit trail purposes.
        /// </remarks>
        [DefaultValue(true)]
        public bool IsActive { get; set; } = true;
    }
}
