// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShimsServer.Context;

#nullable disable

namespace ShimsServer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260414134514_DiagnosesRewrite5_1")]
    partial class DiagnosesRewrite5_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("concurrencystamp");

                    b.Property<string>("Name")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("normalizedname");

                    b.HasKey("Id")
                        .HasName("pk_aspnetroles");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("aspnetroles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("claimtype");

                    b.Property<string>("ClaimValue")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("claimvalue");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("roleid");

                    b.HasKey("Id")
                        .HasName("pk_aspnetroleclaims");

                    b.HasIndex("RoleId");

                    b.ToTable("aspnetroleclaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("claimtype");

                    b.Property<string>("ClaimValue")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("claimvalue");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("pk_aspnetuserclaims");

                    b.HasIndex("UserId");

                    b.ToTable("aspnetuserclaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("loginprovider");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("providerkey");

                    b.Property<string>("ProviderDisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("providerdisplayname");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_aspnetuserlogins");

                    b.HasIndex("UserId");

                    b.ToTable("aspnetuserlogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("roleid");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_aspnetuserroles");

                    b.HasIndex("RoleId");

                    b.ToTable("aspnetuserroles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("loginprovider");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_aspnetusertokens");

                    b.ToTable("aspnetusertokens", (string)null);
                });

            modelBuilder.Entity("ShimsServer.Context.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("accessfailedcount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("concurrencystamp");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("emailconfirmed");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("fullname");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockoutenabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockoutend");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("normalizedemail");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("normalizedusername");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(168)
                        .HasColumnType("character varying(168)")
                        .HasColumnName("passwordhash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("phonenumber");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phonenumberconfirmed");

                    b.Property<string>("SecurityStamp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("securitystamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("twofactorenabled");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_aspnetusers");

                    b.HasAlternateKey("UserName")
                        .HasName("ak_aspnetusers_username");

                    b.HasIndex("NormalizedEmail");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique();

                    b.ToTable("aspnetusers", (string)null);
                });

            modelBuilder.Entity("ShimsServer.Models.Accounts.Payments", b =>
                {
                    b.Property<Guid>("PaymentsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("paymentsid");

                    b.Property<decimal>("Attendance")
                        .HasColumnType("numeric")
                        .HasColumnName("attendance");

                    b.Property<decimal>("Cash")
                        .HasColumnType("numeric")
                        .HasColumnName("cash");

                    b.Property<decimal>("Drugs")
                        .HasColumnType("numeric")
                        .HasColumnName("drugs");

                    b.PrimitiveCollection<Guid[]>("DrugsList")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("drugslist");

                    b.Property<decimal>("Labs")
                        .HasColumnType("numeric")
                        .HasColumnName("labs");

                    b.PrimitiveCollection<Guid[]>("LabsList")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("labslist");

                    b.Property<decimal>("MobileMoney")
                        .HasColumnType("numeric")
                        .HasColumnName("mobilemoney");

                    b.Property<Guid?>("PatientAttendancesID")
                        .HasColumnType("uuid")
                        .HasColumnName("patientattendancesid");

                    b.Property<Guid>("PatientsAttendancesID")
                        .HasColumnType("uuid")
                        .HasColumnName("patientsattendancesid");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paymentdate");

                    b.Property<decimal>("Registration")
                        .HasColumnType("numeric")
                        .HasColumnName("registration");

                    b.Property<decimal>("Services")
                        .HasColumnType("numeric")
                        .HasColumnName("services");

                    b.PrimitiveCollection<Guid[]>("ServicesList")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("serviceslist");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("username");

                    b.HasKey("PaymentsID")
                        .HasName("pk_payments");

                    b.HasIndex("PatientAttendancesID");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("ShimsServer.Models.ConsultingRoom.PatientConsultation", b =>
                {
                    b.Property<Guid>("PatientConsultationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("patientconsultationid");

                    b.Property<byte>("AVPU")
                        .HasColumnType("smallint")
                        .HasColumnName("avpu");

                    b.Property<string>("Complaints")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("complaints");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateadded");

                    b.Property<string>("ODQ")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("odq");

                    b.Property<Guid?>("PatientAttendancesID")
                        .HasColumnType("uuid")
                        .HasColumnName("patientattendancesid");

                    b.Property<Guid>("PatientsAttendancesID")
                        .HasColumnType("uuid")
                        .HasColumnName("patientsattendancesid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("username");

                    b.HasKey("PatientConsultationID")
                        .HasName("pk_patientconsultations");

                    b.HasIndex("PatientAttendancesID");

                    b.ToTable("patientconsultations", (string)null);
                });

            modelBuilder.Entity("ShimsServer.Models.ConsultingRoom.PatientDiagnosis", b =>
                {
                    b.Property<Guid>("PatientDiagnosisID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("patientdiagnosisid");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateadded");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<Guid?>("DiagnosesID")
                        .HasColumnType("uuid")
                        .HasColumnName("diagnosesid");

                    b.Property<Guid>("DiagnosisID")
                        .HasColumnType("uuid")
                        .HasColumnName("diagnosisid");

                    b.Property<Guid?>("PatientAttendancesID")
                        .HasColumnType("uuid")
                        .HasColumnName("patientattendancesid");

                    b.Property<Guid>("PatientsAttendancesID")
                        .HasColumnType("uuid")
                        .HasColumnName("patientsattendancesid");

                    b.PrimitiveCollection<Guid[]>("SecondaryDiagnoses")
                        .HasColumnType("uuid[]")
                        .HasColumnName("secondarydiagnoses");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("username");

                    b.HasKey("PatientDiagnosisID")
                        .HasName("pk_patientdiagnoses");

                    b.HasIndex("DiagnosesID");

                    b.HasIndex("PatientAttendancesID");

                    b.ToTable("patientdiagnoses", (string)null);
                });

            modelBuilder.Entity("ShimsServer.Models.ConsultingRoom.PatientOutcomes", b =>
                {
                    b.Property<Guid>("PatientsAttendancesID")
                        .HasColumnType("uuid")
                        .HasColumnName("patientsattendancesid");

                    b.Property<string>("Notes")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("notes");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("outcome");

                    b.Property<DateTime>("OutcomeDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("outcomedate");

                    b.HasKey("PatientsAttendancesID")
                        .HasName("pk_patientoutcomes");

                    b.ToTable("patientoutcomes", (string)null);
                });

            modelBuilder.Entity("ShimsServer.Models.ConsultingRoom.PatientSignsAndSymptoms", b =>
                {
                    b.Property<Guid>("PatientSignsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("patientsignsid");

                    b.Property<string>("SignAndSymptoms")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("signandsymptoms");

                    b.HasKey("PatientSignsID")
                        .HasName("pk_patientsignsandsymptoms");

                    b.ToTable("patientsignsandsymptoms", (string)null);
                });

            modelBuilder.Entity("ShimsServer.Models.Diagnoses", b =>
                {
                    b.Property<Guid>("DiagnosesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("diagnosesid");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("description");

                    b.Property<string>("DiagnosisName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("diagnosisname");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.PrimitiveCollection<string[]>("Levels")
                        .IsRequired()
                        .HasColumnType("varchar(5)[]")
                        .HasColumnName("levels");

                    b.Property<string>("SubCategory")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subcategory");

                    b.HasKey("DiagnosesID")
                        .HasName("pk_diagnoses");

                    b.HasIndex("DiagnosisName", "Category", "SubCategory");

                    b.ToTable("diagnoses", (string)null);
                });

            modelBuilder.Entity("ShimsServer.Models.Drugs.Dispensing", b =>
                {
                    b.Property<Guid>("DrugPaymentsID")
                        .HasColumnType("uuid")
                        .HasColumnName("drugpaymentsid");

                    b.Property<DateTime>("DateDispensed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datedispensed");

                    b.Property<byte>("QuantityDispensed")
                        .HasColumnType("smallint")
                        .HasColumnName("quantitydispensed");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("username");

                    b.HasKey("DrugPaymentsID")
                        .HasName("pk_dispensings");

                    b.ToTable("dispensings", (string)null);
                });

            modelBuilder.Entity("ShimsServer.Models.Drugs.DispensingCalculations", b =>
                {
                    b.Property<Guid>("DrugsRequestsID")
                        .HasColumnType("uuid")
                        .HasColumnName("drugsrequestsid");

                    b.Property<DateTime>("DateDone")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datedone");

                    b.Property<string>("Notes")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("notes");

                    b.Property<byte>("Quantity")
                        .HasColumnType("smallint")
                        .HasColumnName("quantity");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("username");

                    b.HasKey("DrugsRequestsID")
                        .HasName("pk_dispensingcalculations");

                    b.ToTable("dispensingcalculations", (string)null);
                });

            modelBuilder.Entity("ShimsServer.Models.Drugs.DrugPayments", b =>
                {
                    b.Property<Guid>("DispensingCaculationsID")
                        .HasColumnType("uuid")
                        .HasColumnName("dispensingcaculationsid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("DatePaid")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datepaid");

                    b.Property<Guid?>("PaymentTypesID")
                        .HasColumnType("uuid")
                        .HasColumnName("paymenttypesid");

                    b.Property<byte>("QuantityPaid")
                        .HasColumnType("smallint")
                        .HasColumnName("quantitypaid");

                    b.Property<string>("Receipt")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("receipt");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("username");

                    b.HasKey("DispensingCaculationsID")
                        .HasName("pk_drugpayments");

                    b.ToTable("drugpayments", (string)null);
                });

            modelBuilder.Entity("ShimsServer.Models.Drugs.Drugs", b =>
                {
                    b.Property<Guid>("DrugsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("drugsid");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateadded");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Drug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("drug");

                    b.Property<string>("Tags")
                        .HasColumnType("text")
                        .HasColumnName("tags");

                    b.HasKey("DrugsID")
                        .HasName("pk_drugs");

                    b.ToTable("drugs", (string)null);
                });

            modelBuilder.Entity("ShimsServer.Models.Drugs.DrugsRequests", b =>
                {
                    b.Property<Guid>("DrugsRequestsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("drugsrequestsid");

                    b.Property<DateTime>("DateRequested")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("daterequested");

                    b.Property<byte>("Days")
                        .HasColumnType("smallint")
                        .HasColumnName("days");

                    b.Property<Guid?>("DrugsID")
                        .HasColumnType("uuid")
                        .HasColumnName("drugsid");

                    b.Property<byte>("Frequency")
                        .HasColumnType("smallint")
                        .HasColumnName("frequency");

                    b.Property<bool>("IsDispensed")
                        .HasColumnType("boolean")
                        .HasColumnName("isdispensed");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean")
                        .HasColumnName("ispaid");

                    b.Property<Guid>("PatientsAttendancesID")
                        .HasColumnType("uuid")
                        .HasColumnName("patientsattendancesid");

                    b.Property<byte>("QuantityRequested")
                        .HasColumnType("smallint")
                        .HasColumnName("quantityrequested");

                    b.Property<Guid>("SchemeDrugsID")
                        .HasColumnType("uuid")
                        .HasColumnName("schemedrugsid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("username");

                    b.HasKey("DrugsRequestsID")
                        .HasName("pk_drugsrequests");

                    b.HasIndex("DrugsID");

                    b.HasIndex("PatientsAttendancesID");

                    b.HasIndex("SchemeDrugsID");

                    b.ToTable("drugsrequests", (string)null);
                });

            modelBuilder.Entity("ShimsServer.Models.Drugs.DrugsStock", b =>
                {
                    b.Property<Guid>("DrugsStockID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("drugsstockid");

                    b.Property<Guid>("DrugsID")
                        .HasColumnType("uuid")
                        .HasColumnName("drugsid");

                    b.Property<short>("Quantity")
                        .HasColumnType("smallint")
                        .HasColumnName("quantity");

                    b.Property<DateTime>("TranDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trandate");

                    b.HasKey("DrugsStockID")
                        .HasName("pk_drugsstocks");

                    b.HasIndex("DrugsID");

                    b.ToTable("drugsstocks", (string)null);
                });

            modelBuilder.Entity("ShimsServer.Models.Labs.InvestigationParameters", b =>
                {
                    b.Property<Guid>("InvestigationParametersID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("investigationparametersid");

                    b.Property<string>("InvestigationParameter")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("investigationparameter");

                    b.Property<int>("InvestigationsID")
                        .HasColumnType("integer")
                        .HasColumnName("investigationsid");

                    b.Property<Guid?>("InvestigationsID1")
                        .HasColumnType("uuid")
                        .HasColumnName("investigationsid1");

                    b.Property<short>("ParameterOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("parameterorder");

                    b.HasKey("InvestigationParametersID")
                        .HasName("pk_investigationparameters");

                    b.HasIndex("InvestigationsID1");

                    b.ToTable("investigationparameters", (string)null);
                });

            modelBuilder.Entity("ShimsServer.Models.Labs.Investigations", b =>
                {
                    b.Property<Guid>("InvestigationsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("investigationsid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<string>("Investigation")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("investigation");

                    b.Property<string>("InvestigationType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("investigationtype");

                    b.Property<string>("LabDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("labdescription");

                    b.PrimitiveCollection<string[]>("Levels")
                        .IsRequired()
                        .HasColumnType("varchar(5)[]")
                        .HasColumnName("levels");

                    b.HasKey("InvestigationsID")
                        .HasName("pk_investigations");

                    b.ToTable("investigations", (string)null);
                });

            modelBuilder.Entity("ShimsServer.Models.Labs.InvestigationsPayment", b =>
                {
                    b.Property<Guid>("InvestigationsRequestsID")
                        .HasColumnType("uuid")
                        .HasColumnName("investigationsrequestsid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("DatePaid")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datepaid");

                    b.Property<string>("PaymentReceiver")
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("paymentreceiver");

                    b.Property<Guid?>("PaymentTypesID")
                        .HasColumnType("uuid")
                        .HasColumnName("paymenttypesid");

                    b.Property<string>("Receipt")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("receipt");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("username");

                    b.HasKey("InvestigationsRequestsID")
                        .HasName("pk_investigationspayments");

                    b.ToTable("investigationspayments", (string)null);
                });

            modelBuilder.Entity("ShimsServer.Models.Labs.InvestigationsRequests", b =>
                {
                    b.Property<Guid>("LabRequestsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("labrequestsid");

                    b.Property<DateTime>("DateRequested")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("daterequested");

                    b.Property<Guid?>("PatientAttendancesID")
                        .HasColumnType("uuid")
                        .HasColumnName("patientattendancesid");

                    b.Property<Guid>("PatientsAttendancesID")
                        .HasColumnType("uuid")
                        .HasColumnName("patientsattendancesid");

                    b.Property<Guid>("SchemeLabsID")
                        .HasColumnType("uuid")
                        .HasColumnName("schemelabsid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("username");

                    b.HasKey("LabRequestsID")
                        .HasName("pk_investigationsrequests");

                    b.HasIndex("PatientAttendancesID");

                    b.HasIndex("SchemeLabsID");

                    b.ToTable("investigationsrequests", (string)null);
                });

            modelBuilder.Entity("ShimsServer.Models.Labs.InvestigationsResults", b =>
                {
                    b.Property<Guid>("InvestigationsPaymentID")
                        .HasColumnType("uuid")
                        .HasColumnName("investigationspaymentid");

                    b.Property<DateTime>("DateTested")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datetested");

                    b.Property<Guid>("LabParametersID")
                        .HasColumnType("uuid")
                        .HasColumnName("labparametersid");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("result");

                    b.Property<string>("ServerName")
                        .HasColumnType("text")
                        .HasColumnName("servername");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("username");

                    b.HasKey("InvestigationsPaymentID")
                        .HasName("pk_investigationsresults");

                    b.HasIndex("LabParametersID");

                    b.ToTable("investigationsresults", (string)null);
                });

            modelBuilder.Entity("ShimsServer.Models.OPD.Vitals", b =>
                {
                    b.Property<Guid>("VitalsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("vitalsid");

                    b.Property<string>("Complaints")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("complaints");

                    b.Property<DateTime>("DateSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateseen");

                    b.Property<double>("Diastol")
                        .HasColumnType("double precision")
                        .HasColumnName("diastol");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("notes");

                    b.Property<Guid?>("PatientAttendancesID")
                        .HasColumnType("uuid")
                        .HasColumnName("patientattendancesid");

                    b.Property<Guid>("PatientsAttendancesID")
                        .HasColumnType("uuid")
                        .HasColumnName("patientsattendancesid");

                    b.Property<double>("Pulse")
                        .HasColumnType("double precision")
                        .HasColumnName("pulse");

                    b.Property<double>("Respiration")
                        .HasColumnType("double precision")
                        .HasColumnName("respiration");

                    b.Property<double?>("SPO2")
                        .HasColumnType("double precision")
                        .HasColumnName("spo2");

                    b.Property<double>("Systol")
                        .HasColumnType("double precision")
                        .HasColumnName("systol");

                    b.Property<double>("Temperature")
                        .HasColumnType("double precision")
                        .HasColumnName("temperature");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("username");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision")
                        .HasColumnName("weight");

                    b.HasKey("VitalsID")
                        .HasName("pk_vitals");

                    b.HasIndex("PatientAttendancesID");

                    b.ToTable("vitals", (string)null);
                });

            modelBuilder.Entity("ShimsServer.Models.Records.PatientAttendance", b =>
                {
                    b.Property<Guid>("PatientAttendancesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("patientattendancesid");

                    b.Property<DateTime>("DateSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateseen");

                    b.Property<Guid>("PatientSchemesID")
                        .HasColumnType("uuid")
                        .HasColumnName("patientschemesid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("username");

                    b.Property<string>("VisitType")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("visittype");

                    b.HasKey("PatientAttendancesID")
                        .HasName("pk_patientattendances");

                    b.HasIndex("PatientSchemesID");

                    b.ToTable("patientattendances", (string)null);
                });

            modelBuilder.Entity("ShimsServer.Models.Records.PatientSchemes", b =>
                {
                    b.Property<Guid>("PatientSchemesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("patientschemesid");

                    b.Property<string>("CardID")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("cardid");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expirydate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastupdatedate");

                    b.Property<Guid>("PatientsID")
                        .HasColumnType("uuid")
                        .HasColumnName("patientsid");

                    b.Property<Guid>("SchemesID")
                        .HasColumnType("uuid")
                        .HasColumnName("schemesid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("username");

                    b.HasKey("PatientSchemesID")
                        .HasName("pk_patientschemes");

                    b.ToTable("patientschemes", (string)null);
                });

            modelBuilder.Entity("ShimsServer.Models.Records.Patients", b =>
                {
                    b.Property<Guid>("PatientsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("patientsid");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateofbirth");

                    b.Property<string>("GhanaCard")
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)")
                        .HasColumnName("ghanacard");

                    b.Property<string>("HospitalID")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hospitalid");

                    b.Property<string>("OtherNames")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("othernames");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phonenumber");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("sex");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("surname");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("username");

                    b.HasKey("PatientsID")
                        .HasName("pk_patients");

                    b.ToTable("patients", (string)null);
                });

            modelBuilder.Entity("ShimsServer.Models.SchemeDiagnoses", b =>
                {
                    b.Property<Guid>("SchemeDiagnosesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("schemediagnosesid");

                    b.Property<DateTime>("DateSet")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateset");

                    b.Property<Guid>("DiagnosesID")
                        .HasColumnType("uuid")
                        .HasColumnName("diagnosesid");

                    b.Property<string>("GDRG")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gdrg");

                    b.Property<string>("ICDCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("icdcode");

                    b.Property<string>("ICDVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("icdversion");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<Guid>("SchemesID")
                        .HasColumnType("uuid")
                        .HasColumnName("schemesid");

                    b.Property<string>("Snomed")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("snomed");

                    b.Property<decimal>("Tariff")
                        .HasColumnType("numeric")
                        .HasColumnName("tariff");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("username");

                    b.Property<string>("Variation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("variation");

                    b.HasKey("SchemeDiagnosesID")
                        .HasName("pk_schemediagnoses");

                    b.HasIndex("DiagnosesID");

                    b.HasIndex("SchemesID");

                    b.ToTable("schemediagnoses", (string)null);
                });

            modelBuilder.Entity("ShimsServer.Models.Schemes.SchemeDrugs", b =>
                {
                    b.Property<Guid>("SchemeDrugsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("schemedrugsid");

                    b.Property<DateTime>("DateSet")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateset");

                    b.Property<string>("DosageForm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("dosageform");

                    b.Property<string>("DrugCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("drugcode");

                    b.Property<Guid>("DrugsID")
                        .HasColumnType("uuid")
                        .HasColumnName("drugsid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<string>("PrescriptionLevel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("prescriptionlevel");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<string>("PricingUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("pricingunit");

                    b.Property<Guid>("SchemesID")
                        .HasColumnType("uuid")
                        .HasColumnName("schemesid");

                    b.Property<string>("Strength")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("strength");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("username");

                    b.HasKey("SchemeDrugsID")
                        .HasName("pk_schemedrugs");

                    b.HasIndex("DrugsID");

                    b.HasIndex("SchemesID");

                    b.HasIndex("DrugCode", "DateSet", "DosageForm", "Strength", "PricingUnit");

                    b.ToTable("schemedrugs", (string)null);
                });

            modelBuilder.Entity("ShimsServer.Models.Schemes.SchemeInvestigations", b =>
                {
                    b.Property<Guid>("SchemeInvestigationsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("schemeinvestigationsid");

                    b.Property<DateTime>("DateSet")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateset");

                    b.Property<string>("GDRG")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gdrg");

                    b.Property<Guid>("InvestigationsID")
                        .HasColumnType("uuid")
                        .HasColumnName("investigationsid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<Guid>("SchemesID")
                        .HasColumnType("uuid")
                        .HasColumnName("schemesid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("username");

                    b.HasKey("SchemeInvestigationsID")
                        .HasName("pk_schemeinvestigations");

                    b.HasIndex("InvestigationsID");

                    b.HasIndex("SchemesID");

                    b.ToTable("schemeinvestigations", (string)null);
                });

            modelBuilder.Entity("ShimsServer.Models.Schemes.SchemeServices", b =>
                {
                    b.Property<Guid>("SchemeServicesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("schemeservicesid");

                    b.PrimitiveCollection<string[]>("AllowedTiers")
                        .IsRequired()
                        .HasColumnType("varchar(3)[]")
                        .HasColumnName("allowedtiers");

                    b.Property<DateTime>("DateSet")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateset");

                    b.Property<string>("GDRG")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gdrg");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<string>("Narration")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("narration");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<Guid>("SchemesID")
                        .HasColumnType("uuid")
                        .HasColumnName("schemesid");

                    b.Property<Guid>("ServicesID")
                        .HasColumnType("uuid")
                        .HasColumnName("servicesid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("username");

                    b.HasKey("SchemeServicesID")
                        .HasName("pk_schemeservices");

                    b.HasIndex("SchemesID");

                    b.HasIndex("ServicesID");

                    b.ToTable("schemeservices", (string)null);
                });

            modelBuilder.Entity("ShimsServer.Models.Schemes.Schemes", b =>
                {
                    b.Property<Guid>("SchemesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("schemesid");

                    b.Property<string>("Coverage")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("coverage");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<decimal>("MaxPayable")
                        .HasColumnType("numeric")
                        .HasColumnName("maxpayable");

                    b.Property<decimal>("Recovery")
                        .HasColumnType("numeric")
                        .HasColumnName("recovery");

                    b.Property<string>("SchemeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("schemename");

                    b.HasKey("SchemesID")
                        .HasName("pk_schemes");

                    b.ToTable("schemes", (string)null);
                });

            modelBuilder.Entity("ShimsServer.Models.Services.ServicePayment", b =>
                {
                    b.Property<Guid>("ServiceRequestID")
                        .HasColumnType("uuid")
                        .HasColumnName("servicerequestid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("DatePaid")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datepaid");

                    b.Property<Guid>("PatientsAttendancesID")
                        .HasColumnType("uuid")
                        .HasColumnName("patientsattendancesid");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("paymentmethod");

                    b.Property<string>("Receipt")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("receipt");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("username");

                    b.HasKey("ServiceRequestID")
                        .HasName("pk_servicepayments");

                    b.ToTable("servicepayments", (string)null);
                });

            modelBuilder.Entity("ShimsServer.Models.Services.ServiceRendering", b =>
                {
                    b.Property<Guid>("ServicePaymentID")
                        .HasColumnType("uuid")
                        .HasColumnName("servicepaymentid");

                    b.Property<DateTime>("DateServed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateserved");

                    b.Property<Guid>("PatientsAttendancesID")
                        .HasColumnType("uuid")
                        .HasColumnName("patientsattendancesid");

                    b.Property<string>("Report")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("report");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("username");

                    b.HasKey("ServicePaymentID")
                        .HasName("pk_servicerenderings");

                    b.ToTable("servicerenderings", (string)null);
                });

            modelBuilder.Entity("ShimsServer.Models.Services.ServiceRequest", b =>
                {
                    b.Property<Guid>("ServiceRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("servicerequestid");

                    b.Property<DateTime>("DateRequested")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("daterequested");

                    b.Property<byte>("Frequency")
                        .HasColumnType("smallint")
                        .HasColumnName("frequency");

                    b.Property<Guid?>("PatientAttendancesID")
                        .HasColumnType("uuid")
                        .HasColumnName("patientattendancesid");

                    b.Property<Guid>("PatientsAttendancesID")
                        .HasColumnType("uuid")
                        .HasColumnName("patientsattendancesid");

                    b.Property<Guid>("SchemeServicesID")
                        .HasColumnType("uuid")
                        .HasColumnName("schemeservicesid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("username");

                    b.HasKey("ServiceRequestID")
                        .HasName("pk_servicerequests");

                    b.HasIndex("PatientAttendancesID");

                    b.HasIndex("SchemeServicesID");

                    b.ToTable("servicerequests", (string)null);
                });

            modelBuilder.Entity("ShimsServer.Models.Services.Services", b =>
                {
                    b.Property<Guid>("ServicesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("servicesid");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("service");

                    b.Property<string>("ServiceGroup")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("servicegroup");

                    b.HasKey("ServicesID")
                        .HasName("pk_services");

                    b.ToTable("services", (string)null);
                });

            modelBuilder.Entity("ShimsServer.Models.Wards.WardAdmissions", b =>
                {
                    b.Property<Guid>("WardAdmissionsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("wardadmissionsid");

                    b.Property<DateTime>("DateAdmitted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateadmitted");

                    b.Property<DateTime?>("DateDischarged")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datedischarged");

                    b.Property<Guid?>("PatientAttendancesID")
                        .HasColumnType("uuid")
                        .HasColumnName("patientattendancesid");

                    b.Property<Guid>("PatientsAttendancesID")
                        .HasColumnType("uuid")
                        .HasColumnName("patientsattendancesid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("username");

                    b.Property<Guid>("WardsID")
                        .HasColumnType("uuid")
                        .HasColumnName("wardsid");

                    b.HasKey("WardAdmissionsID")
                        .HasName("pk_wardadmissions");

                    b.HasIndex("PatientAttendancesID");

                    b.HasIndex("WardsID");

                    b.ToTable("wardadmissions", (string)null);
                });

            modelBuilder.Entity("ShimsServer.Models.Wards.Wards", b =>
                {
                    b.Property<Guid>("WardsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("wardsid");

                    b.Property<short>("Capacity")
                        .HasColumnType("smallint")
                        .HasColumnName("capacity");

                    b.Property<string>("Ward")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ward");

                    b.Property<string>("WardTags")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("wardtags");

                    b.HasKey("WardsID")
                        .HasName("pk_wards");

                    b.HasIndex("Ward")
                        .IsUnique();

                    b.ToTable("wards", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_aspnetroleclaims_aspnetroles_roleid");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("ShimsServer.Context.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_aspnetuserclaims_aspnetusers_userid");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("ShimsServer.Context.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_aspnetuserlogins_aspnetusers_userid");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_aspnetuserroles_aspnetroles_roleid");

                    b.HasOne("ShimsServer.Context.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_aspnetuserroles_aspnetusers_userid");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ShimsServer.Context.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_aspnetusertokens_aspnetusers_userid");
                });

            modelBuilder.Entity("ShimsServer.Models.Accounts.Payments", b =>
                {
                    b.HasOne("ShimsServer.Models.Records.PatientAttendance", "PatientAttendance")
                        .WithMany()
                        .HasForeignKey("PatientAttendancesID")
                        .HasConstraintName("fk_payments_patientattendances_patientattendancesid");

                    b.Navigation("PatientAttendance");
                });

            modelBuilder.Entity("ShimsServer.Models.ConsultingRoom.PatientConsultation", b =>
                {
                    b.HasOne("ShimsServer.Models.Records.PatientAttendance", "PatientAttendance")
                        .WithMany()
                        .HasForeignKey("PatientAttendancesID")
                        .HasConstraintName("fk_patientconsultations_patientattendances_patientattendancesid");

                    b.Navigation("PatientAttendance");
                });

            modelBuilder.Entity("ShimsServer.Models.ConsultingRoom.PatientDiagnosis", b =>
                {
                    b.HasOne("ShimsServer.Models.Diagnoses", "Diagnoses")
                        .WithMany()
                        .HasForeignKey("DiagnosesID")
                        .HasConstraintName("fk_patientdiagnoses_diagnoses_diagnosesid");

                    b.HasOne("ShimsServer.Models.Records.PatientAttendance", "PatientAttendance")
                        .WithMany()
                        .HasForeignKey("PatientAttendancesID")
                        .HasConstraintName("fk_patientdiagnoses_patientattendances_patientattendancesid");

                    b.Navigation("Diagnoses");

                    b.Navigation("PatientAttendance");
                });

            modelBuilder.Entity("ShimsServer.Models.ConsultingRoom.PatientOutcomes", b =>
                {
                    b.HasOne("ShimsServer.Models.Records.PatientAttendance", "PatientAttendance")
                        .WithMany()
                        .HasForeignKey("PatientsAttendancesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_patientoutcomes_patientattendances_patientsattendancesid");

                    b.Navigation("PatientAttendance");
                });

            modelBuilder.Entity("ShimsServer.Models.Drugs.Dispensing", b =>
                {
                    b.HasOne("ShimsServer.Models.Drugs.DrugPayments", "DrugPayments")
                        .WithOne("Dispensing")
                        .HasForeignKey("ShimsServer.Models.Drugs.Dispensing", "DrugPaymentsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dispensings_drugpayments_drugpaymentsid");

                    b.Navigation("DrugPayments");
                });

            modelBuilder.Entity("ShimsServer.Models.Drugs.DispensingCalculations", b =>
                {
                    b.HasOne("ShimsServer.Models.Drugs.DrugsRequests", "DrugsRequests")
                        .WithOne("DispensingCalculations")
                        .HasForeignKey("ShimsServer.Models.Drugs.DispensingCalculations", "DrugsRequestsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dispensingcalculations_drugsrequests_drugsrequestsid");

                    b.Navigation("DrugsRequests");
                });

            modelBuilder.Entity("ShimsServer.Models.Drugs.DrugPayments", b =>
                {
                    b.HasOne("ShimsServer.Models.Drugs.DispensingCalculations", "DispensingCalculations")
                        .WithOne("DrugPayments")
                        .HasForeignKey("ShimsServer.Models.Drugs.DrugPayments", "DispensingCaculationsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_drugpayments_dispensingcalculations_dispensingcaculationsid");

                    b.Navigation("DispensingCalculations");
                });

            modelBuilder.Entity("ShimsServer.Models.Drugs.DrugsRequests", b =>
                {
                    b.HasOne("ShimsServer.Models.Drugs.Drugs", null)
                        .WithMany("PatientDrugs")
                        .HasForeignKey("DrugsID")
                        .HasConstraintName("fk_drugsrequests_drugs_drugsid");

                    b.HasOne("ShimsServer.Models.Records.PatientAttendance", "PatientsAttendances")
                        .WithMany()
                        .HasForeignKey("PatientsAttendancesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_drugsrequests_patientattendances_patientsattendancesid");

                    b.HasOne("ShimsServer.Models.Schemes.SchemeDrugs", "SchemeDrugs")
                        .WithMany("DrugsRequests")
                        .HasForeignKey("SchemeDrugsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_drugsrequests_schemedrugs_schemedrugsid");

                    b.Navigation("PatientsAttendances");

                    b.Navigation("SchemeDrugs");
                });

            modelBuilder.Entity("ShimsServer.Models.Drugs.DrugsStock", b =>
                {
                    b.HasOne("ShimsServer.Models.Drugs.Drugs", "Drugs")
                        .WithMany("DrugsStocks")
                        .HasForeignKey("DrugsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_drugsstocks_drugs_drugsid");

                    b.Navigation("Drugs");
                });

            modelBuilder.Entity("ShimsServer.Models.Labs.InvestigationParameters", b =>
                {
                    b.HasOne("ShimsServer.Models.Labs.Investigations", "Investigations")
                        .WithMany("LabParameters")
                        .HasForeignKey("InvestigationsID1")
                        .HasConstraintName("fk_investigationparameters_investigations_investigationsid1");

                    b.Navigation("Investigations");
                });

            modelBuilder.Entity("ShimsServer.Models.Labs.InvestigationsPayment", b =>
                {
                    b.HasOne("ShimsServer.Models.Labs.InvestigationsRequests", "LabRequests")
                        .WithOne("LabPayment")
                        .HasForeignKey("ShimsServer.Models.Labs.InvestigationsPayment", "InvestigationsRequestsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_investigationspayments_investigationsrequests_investigation~");

                    b.Navigation("LabRequests");
                });

            modelBuilder.Entity("ShimsServer.Models.Labs.InvestigationsRequests", b =>
                {
                    b.HasOne("ShimsServer.Models.Records.PatientAttendance", "PatientAttendance")
                        .WithMany()
                        .HasForeignKey("PatientAttendancesID")
                        .HasConstraintName("fk_investigationsrequests_patientattendances_patientattendance~");

                    b.HasOne("ShimsServer.Models.Schemes.SchemeInvestigations", "SchemeLabs")
                        .WithMany("InvestigationsRequests")
                        .HasForeignKey("SchemeLabsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_investigationsrequests_schemeinvestigations_schemelabsid");

                    b.Navigation("PatientAttendance");

                    b.Navigation("SchemeLabs");
                });

            modelBuilder.Entity("ShimsServer.Models.Labs.InvestigationsResults", b =>
                {
                    b.HasOne("ShimsServer.Models.Labs.InvestigationsPayment", "InvestigationsPayment")
                        .WithOne("LabResults")
                        .HasForeignKey("ShimsServer.Models.Labs.InvestigationsResults", "InvestigationsPaymentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_investigationsresults_investigationspayments_investigations~");

                    b.HasOne("ShimsServer.Models.Labs.InvestigationParameters", "InvestigationParameters")
                        .WithMany()
                        .HasForeignKey("LabParametersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_investigationsresults_investigationparameters_labparameters~");

                    b.Navigation("InvestigationParameters");

                    b.Navigation("InvestigationsPayment");
                });

            modelBuilder.Entity("ShimsServer.Models.OPD.Vitals", b =>
                {
                    b.HasOne("ShimsServer.Models.Records.PatientAttendance", "PatientAttendance")
                        .WithMany()
                        .HasForeignKey("PatientAttendancesID")
                        .HasConstraintName("fk_vitals_patientattendances_patientattendancesid");

                    b.Navigation("PatientAttendance");
                });

            modelBuilder.Entity("ShimsServer.Models.Records.PatientAttendance", b =>
                {
                    b.HasOne("ShimsServer.Models.Records.PatientSchemes", "PatientSchemes")
                        .WithMany()
                        .HasForeignKey("PatientSchemesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_patientattendances_patientschemes_patientschemesid");

                    b.Navigation("PatientSchemes");
                });

            modelBuilder.Entity("ShimsServer.Models.SchemeDiagnoses", b =>
                {
                    b.HasOne("ShimsServer.Models.Diagnoses", "Diagnoses")
                        .WithMany("SchemeDiagnoses")
                        .HasForeignKey("DiagnosesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_schemediagnoses_diagnoses_diagnosesid");

                    b.HasOne("ShimsServer.Models.Schemes.Schemes", "Schemes")
                        .WithMany()
                        .HasForeignKey("SchemesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_schemediagnoses_schemes_schemesid");

                    b.Navigation("Diagnoses");

                    b.Navigation("Schemes");
                });

            modelBuilder.Entity("ShimsServer.Models.Schemes.SchemeDrugs", b =>
                {
                    b.HasOne("ShimsServer.Models.Drugs.Drugs", "Drugs")
                        .WithMany()
                        .HasForeignKey("DrugsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_schemedrugs_drugs_drugsid");

                    b.HasOne("ShimsServer.Models.Schemes.Schemes", "Schemes")
                        .WithMany()
                        .HasForeignKey("SchemesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_schemedrugs_schemes_schemesid");

                    b.Navigation("Drugs");

                    b.Navigation("Schemes");
                });

            modelBuilder.Entity("ShimsServer.Models.Schemes.SchemeInvestigations", b =>
                {
                    b.HasOne("ShimsServer.Models.Labs.Investigations", "Investigations")
                        .WithMany("SchemeLabs")
                        .HasForeignKey("InvestigationsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_schemeinvestigations_investigations_investigationsid");

                    b.HasOne("ShimsServer.Models.Schemes.Schemes", "Schemes")
                        .WithMany()
                        .HasForeignKey("SchemesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_schemeinvestigations_schemes_schemesid");

                    b.Navigation("Investigations");

                    b.Navigation("Schemes");
                });

            modelBuilder.Entity("ShimsServer.Models.Schemes.SchemeServices", b =>
                {
                    b.HasOne("ShimsServer.Models.Schemes.Schemes", "Schemes")
                        .WithMany()
                        .HasForeignKey("SchemesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_schemeservices_schemes_schemesid");

                    b.HasOne("ShimsServer.Models.Services.Services", "Services")
                        .WithMany("SchemeServices")
                        .HasForeignKey("ServicesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_schemeservices_services_servicesid");

                    b.Navigation("Schemes");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("ShimsServer.Models.Services.ServicePayment", b =>
                {
                    b.HasOne("ShimsServer.Models.Services.ServiceRequest", "ServiceRequest")
                        .WithOne("ServicePayment")
                        .HasForeignKey("ShimsServer.Models.Services.ServicePayment", "ServiceRequestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_servicepayments_servicerequests_servicerequestid");

                    b.Navigation("ServiceRequest");
                });

            modelBuilder.Entity("ShimsServer.Models.Services.ServiceRendering", b =>
                {
                    b.HasOne("ShimsServer.Models.Services.ServicePayment", "ServicePayment")
                        .WithOne("ServiceRendering")
                        .HasForeignKey("ShimsServer.Models.Services.ServiceRendering", "ServicePaymentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_servicerenderings_servicepayments_servicepaymentid");

                    b.Navigation("ServicePayment");
                });

            modelBuilder.Entity("ShimsServer.Models.Services.ServiceRequest", b =>
                {
                    b.HasOne("ShimsServer.Models.Records.PatientAttendance", "PatientAttendance")
                        .WithMany()
                        .HasForeignKey("PatientAttendancesID")
                        .HasConstraintName("fk_servicerequests_patientattendances_patientattendancesid");

                    b.HasOne("ShimsServer.Models.Schemes.SchemeServices", "SchemeServices")
                        .WithMany("ServiceRequests")
                        .HasForeignKey("SchemeServicesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_servicerequests_schemeservices_schemeservicesid");

                    b.Navigation("PatientAttendance");

                    b.Navigation("SchemeServices");
                });

            modelBuilder.Entity("ShimsServer.Models.Wards.WardAdmissions", b =>
                {
                    b.HasOne("ShimsServer.Models.Records.PatientAttendance", "PatientAttendance")
                        .WithMany()
                        .HasForeignKey("PatientAttendancesID")
                        .HasConstraintName("fk_wardadmissions_patientattendances_patientattendancesid");

                    b.HasOne("ShimsServer.Models.Wards.Wards", "Wards")
                        .WithMany()
                        .HasForeignKey("WardsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wardadmissions_wards_wardsid");

                    b.Navigation("PatientAttendance");

                    b.Navigation("Wards");
                });

            modelBuilder.Entity("ShimsServer.Models.Diagnoses", b =>
                {
                    b.Navigation("SchemeDiagnoses");
                });

            modelBuilder.Entity("ShimsServer.Models.Drugs.DispensingCalculations", b =>
                {
                    b.Navigation("DrugPayments");
                });

            modelBuilder.Entity("ShimsServer.Models.Drugs.DrugPayments", b =>
                {
                    b.Navigation("Dispensing");
                });

            modelBuilder.Entity("ShimsServer.Models.Drugs.Drugs", b =>
                {
                    b.Navigation("DrugsStocks");

                    b.Navigation("PatientDrugs");
                });

            modelBuilder.Entity("ShimsServer.Models.Drugs.DrugsRequests", b =>
                {
                    b.Navigation("DispensingCalculations");
                });

            modelBuilder.Entity("ShimsServer.Models.Labs.Investigations", b =>
                {
                    b.Navigation("LabParameters");

                    b.Navigation("SchemeLabs");
                });

            modelBuilder.Entity("ShimsServer.Models.Labs.InvestigationsPayment", b =>
                {
                    b.Navigation("LabResults");
                });

            modelBuilder.Entity("ShimsServer.Models.Labs.InvestigationsRequests", b =>
                {
                    b.Navigation("LabPayment");
                });

            modelBuilder.Entity("ShimsServer.Models.Schemes.SchemeDrugs", b =>
                {
                    b.Navigation("DrugsRequests");
                });

            modelBuilder.Entity("ShimsServer.Models.Schemes.SchemeInvestigations", b =>
                {
                    b.Navigation("InvestigationsRequests");
                });

            modelBuilder.Entity("ShimsServer.Models.Schemes.SchemeServices", b =>
                {
                    b.Navigation("ServiceRequests");
                });

            modelBuilder.Entity("ShimsServer.Models.Services.ServicePayment", b =>
                {
                    b.Navigation("ServiceRendering");
                });

            modelBuilder.Entity("ShimsServer.Models.Services.ServiceRequest", b =>
                {
                    b.Navigation("ServicePayment");
                });

            modelBuilder.Entity("ShimsServer.Models.Services.Services", b =>
                {
                    b.Navigation("SchemeServices");
                });
#pragma warning restore 612, 618
        }
    }
}
